apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: folder4study
  labels:
    app: kafka
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template: 
    metadata:
      name: kafka
      labels:
        app: kafka
        version: latest
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.13-2.8.1
          ports:
            - name: port
              containerPort: 9092
              protocol: TCP
          env:
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.folder4study:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka.folder4study:9092"