apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: folder4study
  labels:
    app: kafka
    version: latest
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - name: port
      port: 9092
      targetPort: port